# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]



#processors:
#  batch:
  # fallback for running via mac or docker to ensure Infra UI will pick up data
#  resource:
#    attributes:
#      - key: host.id
#        value: localhost
#        action: insert
#  resourcedetection:
#    detectors: [ env, system ]
#    system:
#      hostname_sources: [ "os" ]
#      resource_attributes:
#        host.id:
#          enabled: true
#  resourcedetection/cloud:
#    detectors: [ "gcp", "ec2", "azure" ]
#    timeout: 2s
#    override: false